### ISSUE TITLE
IIS support

### ISSUE THREAD

**Issue by RvdHout** [25th-floor/AWStats-MultiSite-Summary#7]
I have been trying to get this running on a Windows box, without success i have to admit
I installed all modules and requesting index.pl etc all works fine, but for some reason it keeps saying there ar no stats available,

> Sorry, no AWStats site was found for user "%Username%". Either the user is abandoned or there where no statistics generated yet. Concerning the latter please try again in 24 hours.

I think is is a Path issue somewhere, and i believe the script is unable to read the config files... uncommenting 
`# print "Reading $configfile\n";' on line [270](https://github.com/25th-floor/AWStats-MultiSite-Summary/blob/master/index.pl#L270) returns nothing that raises the suspicion something is path related

Anyone has some ideas what i can try to make this work?

**Comment by RvdHout** [comment]
Nevermind, solved it... the include file directive needed full path, eg: 

Include "C:/projects/stats.exampledomain.nl/cgi-bin/awstats.conf"

Include "C:/projects/stats.exampledomain.nl/cgi-bin/awstats.conf.local"

**Comment by RvdHout** [comment]
Hi Andreas,

I stumbled on something else, none of the sorting methods that do not include the &t=alnum querystring work (on IIS) result in a ERR_HTTP2_PROTOCOL_ERROR

**Comment by RvdHout** [comment]
@adepretis 

uncommenting print "Reading $configfile\n";  on line [270](https://github.com/25th-floor/AWStats-MultiSite-Summary/blob/master/index.pl#L270) also breaks the site resulting in this ERR_HTTP2_PROTOCOL_ERROR

**Comment by RvdHout** [comment]
If i include &t= for the sorting methods all is fine....weird, seems &t= has to exist

**Comment by adepretis** [comment]
ERR_HTTP2_PROTOCOL_ERROR is more an indicator for issues with the Webserver/IIS ... AWStats MultiSite Summary does nothing special with HTTP or HTTP2.

Unfortunately I can't really help here because this script was never intendet to run on a Windows platform and I don't have the means to test or debug on Windows.

I would appreciate it though if you could try to fix it an submit a PR.

**Comment by RvdHout** [comment]
If fixed it by simply appending &t=alnum to all sort methods

Sorting seems broken anyway, as there is no ASC or DESC sorting of any kind
